# Generated by Django 5.0.6 on 2024-07-06 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='last_claimed',
        ),
    ]
