# Generated by Django 5.0.6 on 2024-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_purchase_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='last_claimed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='reward_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
